/**
 * Profile API functions
 * Handles tenant-level community profile operations
 */

import { httpClient } from '@/lib/http';
import {
  MyCommunityProfile,
  UpdateProfileRequest,
  UpdatePrivacySettingsRequest,
  UpdateNotificationSettingsRequest,
  TempUploadResponse,
} from '@/types/profile';
import { API_BASE_URL } from '@/config/env';
import { useScopeStore } from '@/lib/store/scope-store';

// ============================================
// API Endpoints
// ============================================

const PROFILE_ENDPOINTS = {
  // Tenant-level profile
  MY_PROFILE: '/api/v1/tenant/me/profile',
  PRIVACY: '/api/v1/tenant/me/profile/privacy',
  NOTIFICATIONS: '/api/v1/tenant/me/profile/notifications',
  // Temp file uploads (tempKey is auto-generated by backend)
  TEMP_UPLOADS: '/api/v1/tenant/files/temp',
} as const;

// ============================================
// GET Operations
// ============================================

/**
 * Fetches the current user's community profile
 * Requires X-Tenant-Id header (set automatically by HTTP client when in tenant scope)
 */
export async function getMyProfile(): Promise<MyCommunityProfile> {
  return httpClient.get<MyCommunityProfile>(PROFILE_ENDPOINTS.MY_PROFILE);
}

// ============================================
// UPDATE Operations
// ============================================

/**
 * Updates display settings (name, about me, photo)
 */
export async function updateProfile(data: UpdateProfileRequest): Promise<void> {
  return httpClient.put<void>(PROFILE_ENDPOINTS.MY_PROFILE, data);
}

/**
 * Updates privacy/directory settings
 */
export async function updatePrivacySettings(
  data: UpdatePrivacySettingsRequest
): Promise<void> {
  return httpClient.put<void>(PROFILE_ENDPOINTS.PRIVACY, data);
}

/**
 * Updates notification preferences
 */
export async function updateNotificationSettings(
  data: UpdateNotificationSettingsRequest
): Promise<void> {
  return httpClient.put<void>(PROFILE_ENDPOINTS.NOTIFICATIONS, data);
}

// ============================================
// FILE UPLOAD Operations
// ============================================

/**
 * Generates a client-side UUID v4 to be used as a temp file key.
 * This key is used to correlate the file upload with the backend.
 * The client generates the key and passes it to the backend as part of the upload flow.
 */
export function generateTempKey(): string {
  return crypto.randomUUID();
}

/**
 * Uploads a file to temporary storage
 * Step 1 of the profile photo upload flow
 * 
 * @param file - The file to upload
 * @param tempKey - The GUID key for this upload (generated via generateTempKey)
 * @param getToken - Function to get the auth token
 * @returns TempUploadResponse with the temp key and file metadata
 */
export async function uploadTempFile(
  file: File,
  tempKey: string,
  getToken: () => Promise<string | null>
): Promise<TempUploadResponse> {
  const formData = new FormData();
  formData.append('file', file);

  // Get auth token and tenant ID
  const token = await getToken();
  const tenantId = useScopeStore.getState().tenantId;

  const headers: HeadersInit = {};
  if (token) {
    headers['Authorization'] = `Bearer ${token}`;
  }
  if (tenantId) {
    headers['X-Tenant-Id'] = tenantId;
  }

  // Pass tempKey as query parameter
  const url = `${API_BASE_URL}${PROFILE_ENDPOINTS.TEMP_UPLOADS}?tempKey=${encodeURIComponent(tempKey)}`;
  
  const response = await fetch(url, {
    method: 'POST',
    headers,
    body: formData,
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(errorData.error || `Upload failed with status ${response.status}`);
  }

  return response.json();
}

