/**
 * Profile types for tenant-level community profile
 * Maps to MyCommunityProfileDto from backend
 */

// ============================================
// Enums
// ============================================

/**
 * Visibility scope for a user in the community directory
 * Values match C# enum integers (not strings)
 */
export enum DirectoryVisibilityScope {
  Hidden = 0,
  BlockOnly = 1,
  Community = 2,
}

// ============================================
// Profile Response
// ============================================

/**
 * Full community profile response from GET /tenant/me/profile
 */
export interface MyCommunityProfile {
  // Core identifiers
  id: string;
  communityUserId: string;

  // Display / Profile settings
  displayName: string | null;
  aboutMe: string | null;
  profilePhotoDocumentId: string | null;
  profilePhotoUrl: string | null;

  // Party information (from linked Party entity)
  partyName: string | null;
  firstName: string | null;
  lastName: string | null;
  primaryEmail: string | null;
  primaryPhone: string | null;

  // Directory & Privacy settings
  directoryVisibility: DirectoryVisibilityScope;
  showInDirectory: boolean;
  showNameInDirectory: boolean;
  showUnitInDirectory: boolean;
  showPhoneInDirectory: boolean;
  showEmailInDirectory: boolean;
  showProfilePhotoInDirectory: boolean;

  // Notification preferences
  pushEnabled: boolean;
  emailEnabled: boolean;
  notifyMaintenanceUpdates: boolean;
  notifyAmenityBookings: boolean;
  notifyVisitorAtGate: boolean;
  notifyAnnouncements: boolean;
  notifyMarketplace: boolean;

  // Timestamps
  createdAt: string;
  updatedAt: string | null;
}

// ============================================
// Update Requests
// ============================================

/**
 * Request to update display settings
 * PUT /tenant/me/profile
 * 
 * Photo upload options:
 * - tempProfilePhoto: Use when uploading a new photo (temp key from temp upload)
 * - profilePhotoDocumentId: Use to reference an existing document
 * - Cannot use both at the same time
 */
export interface UpdateProfileRequest {
  displayName?: string | null;
  aboutMe?: string | null;
  /** Reference to existing document (use one or the other, not both) */
  profilePhotoDocumentId?: string | null;
  /** Temp key from temp upload (use one or the other, not both) */
  tempProfilePhoto?: string | null;
}

/**
 * Response from temp file upload
 * POST /tenant/files/temp
 * Note: tempKey is auto-generated by backend
 */
export interface TempUploadResponse {
  id: string;
  tempKey: string;
  fileName: string;
  contentType: string;
  sizeBytes: number;
  blobPath: string;
  uploadedAt: string;
}

/**
 * Request to update privacy/directory settings
 * PUT /tenant/me/profile/privacy
 */
export interface UpdatePrivacySettingsRequest {
  directoryVisibility: DirectoryVisibilityScope;
  showInDirectory: boolean;
  showNameInDirectory: boolean;
  showUnitInDirectory: boolean;
  showPhoneInDirectory: boolean;
  showEmailInDirectory: boolean;
  showProfilePhotoInDirectory: boolean;
}

/**
 * Request to update notification preferences
 * PUT /tenant/me/profile/notifications
 */
export interface UpdateNotificationSettingsRequest {
  pushEnabled: boolean;
  emailEnabled: boolean;
  notifyMaintenanceUpdates: boolean;
  notifyAmenityBookings: boolean;
  notifyVisitorAtGate: boolean;
  notifyAnnouncements: boolean;
  notifyMarketplace: boolean;
}

// ============================================
// Helper functions
// ============================================

/**
 * Gets a display-friendly name for the user
 */
export function getProfileDisplayName(profile: MyCommunityProfile | null): string {
  if (!profile) return 'User';
  
  // Priority: displayName > partyName > firstName + lastName > email
  if (profile.displayName) return profile.displayName;
  if (profile.partyName) return profile.partyName;
  if (profile.firstName || profile.lastName) {
    return [profile.firstName, profile.lastName].filter(Boolean).join(' ');
  }

  if (profile.primaryEmail) return profile.primaryEmail.split('@')[0];
  
  return 'User';
}

/**
 * Gets initials for avatar fallback
 */
export function getProfileInitials(profile: MyCommunityProfile | null): string {
  if (!profile) return 'U';
  
  const name = getProfileDisplayName(profile);
  const parts = name.split(' ').filter(Boolean);
  
  if (parts.length >= 2) {
    return (parts[0][0] + parts[1][0]).toUpperCase();
  }
  
  return name.slice(0, 2).toUpperCase();
}

/**
 * Gets the directory visibility label
 */
export function getVisibilityLabel(visibility: DirectoryVisibilityScope | number): string {
  // Handle both enum and raw number values from API
  const value = typeof visibility === 'number' ? visibility : Number(visibility);
  
  switch (value) {
    case DirectoryVisibilityScope.Hidden:
      return 'Hidden from directory';
    case DirectoryVisibilityScope.BlockOnly:
      return 'Visible to block residents only';
    case DirectoryVisibilityScope.Community:
      return 'Visible to all community members';
    default:
      return 'Unknown';
  }
}
